require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdministratorsController do

  # This should return the minimal set of attributes required to create a valid
  # Administrator. As you add validations to Administrator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all administrators as @administrators" do
      administrator = Administrator.create! valid_attributes
      get :index
      assigns(:administrators).should eq([administrator])
    end
  end

  describe "GET show" do
    it "assigns the requested administrator as @administrator" do
      administrator = Administrator.create! valid_attributes
      get :show, :id => administrator.id.to_s
      assigns(:administrator).should eq(administrator)
    end
  end

  describe "GET new" do
    it "assigns a new administrator as @administrator" do
      get :new
      assigns(:administrator).should be_a_new(Administrator)
    end
  end

  describe "GET edit" do
    it "assigns the requested administrator as @administrator" do
      administrator = Administrator.create! valid_attributes
      get :edit, :id => administrator.id.to_s
      assigns(:administrator).should eq(administrator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Administrator" do
        expect {
          post :create, :administrator => valid_attributes
        }.to change(Administrator, :count).by(1)
      end

      it "assigns a newly created administrator as @administrator" do
        post :create, :administrator => valid_attributes
        assigns(:administrator).should be_a(Administrator)
        assigns(:administrator).should be_persisted
      end

      it "redirects to the created administrator" do
        post :create, :administrator => valid_attributes
        response.should redirect_to(Administrator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved administrator as @administrator" do
        # Trigger the behavior that occurs when invalid params are submitted
        Administrator.any_instance.stub(:save).and_return(false)
        post :create, :administrator => {}
        assigns(:administrator).should be_a_new(Administrator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Administrator.any_instance.stub(:save).and_return(false)
        post :create, :administrator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested administrator" do
        administrator = Administrator.create! valid_attributes
        # Assuming there are no other administrators in the database, this
        # specifies that the Administrator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Administrator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => administrator.id, :administrator => {'these' => 'params'}
      end

      it "assigns the requested administrator as @administrator" do
        administrator = Administrator.create! valid_attributes
        put :update, :id => administrator.id, :administrator => valid_attributes
        assigns(:administrator).should eq(administrator)
      end

      it "redirects to the administrator" do
        administrator = Administrator.create! valid_attributes
        put :update, :id => administrator.id, :administrator => valid_attributes
        response.should redirect_to(administrator)
      end
    end

    describe "with invalid params" do
      it "assigns the administrator as @administrator" do
        administrator = Administrator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Administrator.any_instance.stub(:save).and_return(false)
        put :update, :id => administrator.id.to_s, :administrator => {}
        assigns(:administrator).should eq(administrator)
      end

      it "re-renders the 'edit' template" do
        administrator = Administrator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Administrator.any_instance.stub(:save).and_return(false)
        put :update, :id => administrator.id.to_s, :administrator => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested administrator" do
      administrator = Administrator.create! valid_attributes
      expect {
        delete :destroy, :id => administrator.id.to_s
      }.to change(Administrator, :count).by(-1)
    end

    it "redirects to the administrators list" do
      administrator = Administrator.create! valid_attributes
      delete :destroy, :id => administrator.id.to_s
      response.should redirect_to(administrators_url)
    end
  end

end
