require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdminPeopleController do

  # This should return the minimal set of attributes required to create a valid
  # AdminPerson. As you add validations to AdminPerson, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_people as @admin_people" do
      admin_person = AdminPerson.create! valid_attributes
      get :index
      assigns(:admin_people).should eq([admin_person])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_person as @admin_person" do
      admin_person = AdminPerson.create! valid_attributes
      get :show, :id => admin_person.id.to_s
      assigns(:admin_person).should eq(admin_person)
    end
  end

  describe "GET new" do
    it "assigns a new admin_person as @admin_person" do
      get :new
      assigns(:admin_person).should be_a_new(AdminPerson)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_person as @admin_person" do
      admin_person = AdminPerson.create! valid_attributes
      get :edit, :id => admin_person.id.to_s
      assigns(:admin_person).should eq(admin_person)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdminPerson" do
        expect {
          post :create, :admin_person => valid_attributes
        }.to change(AdminPerson, :count).by(1)
      end

      it "assigns a newly created admin_person as @admin_person" do
        post :create, :admin_person => valid_attributes
        assigns(:admin_person).should be_a(AdminPerson)
        assigns(:admin_person).should be_persisted
      end

      it "redirects to the created admin_person" do
        post :create, :admin_person => valid_attributes
        response.should redirect_to(AdminPerson.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_person as @admin_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdminPerson.any_instance.stub(:save).and_return(false)
        post :create, :admin_person => {}
        assigns(:admin_person).should be_a_new(AdminPerson)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdminPerson.any_instance.stub(:save).and_return(false)
        post :create, :admin_person => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_person" do
        admin_person = AdminPerson.create! valid_attributes
        # Assuming there are no other admin_people in the database, this
        # specifies that the AdminPerson created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdminPerson.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => admin_person.id, :admin_person => {'these' => 'params'}
      end

      it "assigns the requested admin_person as @admin_person" do
        admin_person = AdminPerson.create! valid_attributes
        put :update, :id => admin_person.id, :admin_person => valid_attributes
        assigns(:admin_person).should eq(admin_person)
      end

      it "redirects to the admin_person" do
        admin_person = AdminPerson.create! valid_attributes
        put :update, :id => admin_person.id, :admin_person => valid_attributes
        response.should redirect_to(admin_person)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_person as @admin_person" do
        admin_person = AdminPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdminPerson.any_instance.stub(:save).and_return(false)
        put :update, :id => admin_person.id.to_s, :admin_person => {}
        assigns(:admin_person).should eq(admin_person)
      end

      it "re-renders the 'edit' template" do
        admin_person = AdminPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdminPerson.any_instance.stub(:save).and_return(false)
        put :update, :id => admin_person.id.to_s, :admin_person => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_person" do
      admin_person = AdminPerson.create! valid_attributes
      expect {
        delete :destroy, :id => admin_person.id.to_s
      }.to change(AdminPerson, :count).by(-1)
    end

    it "redirects to the admin_people list" do
      admin_person = AdminPerson.create! valid_attributes
      delete :destroy, :id => admin_person.id.to_s
      response.should redirect_to(admin_people_url)
    end
  end

end
