require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContentInfosController do

  # This should return the minimal set of attributes required to create a valid
  # ContentInfo. As you add validations to ContentInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all content_infos as @content_infos" do
      content_info = ContentInfo.create! valid_attributes
      get :index
      assigns(:content_infos).should eq([content_info])
    end
  end

  describe "GET show" do
    it "assigns the requested content_info as @content_info" do
      content_info = ContentInfo.create! valid_attributes
      get :show, :id => content_info.id.to_s
      assigns(:content_info).should eq(content_info)
    end
  end

  describe "GET new" do
    it "assigns a new content_info as @content_info" do
      get :new
      assigns(:content_info).should be_a_new(ContentInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested content_info as @content_info" do
      content_info = ContentInfo.create! valid_attributes
      get :edit, :id => content_info.id.to_s
      assigns(:content_info).should eq(content_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContentInfo" do
        expect {
          post :create, :content_info => valid_attributes
        }.to change(ContentInfo, :count).by(1)
      end

      it "assigns a newly created content_info as @content_info" do
        post :create, :content_info => valid_attributes
        assigns(:content_info).should be_a(ContentInfo)
        assigns(:content_info).should be_persisted
      end

      it "redirects to the created content_info" do
        post :create, :content_info => valid_attributes
        response.should redirect_to(ContentInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved content_info as @content_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentInfo.any_instance.stub(:save).and_return(false)
        post :create, :content_info => {}
        assigns(:content_info).should be_a_new(ContentInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentInfo.any_instance.stub(:save).and_return(false)
        post :create, :content_info => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested content_info" do
        content_info = ContentInfo.create! valid_attributes
        # Assuming there are no other content_infos in the database, this
        # specifies that the ContentInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContentInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => content_info.id, :content_info => {'these' => 'params'}
      end

      it "assigns the requested content_info as @content_info" do
        content_info = ContentInfo.create! valid_attributes
        put :update, :id => content_info.id, :content_info => valid_attributes
        assigns(:content_info).should eq(content_info)
      end

      it "redirects to the content_info" do
        content_info = ContentInfo.create! valid_attributes
        put :update, :id => content_info.id, :content_info => valid_attributes
        response.should redirect_to(content_info)
      end
    end

    describe "with invalid params" do
      it "assigns the content_info as @content_info" do
        content_info = ContentInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentInfo.any_instance.stub(:save).and_return(false)
        put :update, :id => content_info.id.to_s, :content_info => {}
        assigns(:content_info).should eq(content_info)
      end

      it "re-renders the 'edit' template" do
        content_info = ContentInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentInfo.any_instance.stub(:save).and_return(false)
        put :update, :id => content_info.id.to_s, :content_info => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested content_info" do
      content_info = ContentInfo.create! valid_attributes
      expect {
        delete :destroy, :id => content_info.id.to_s
      }.to change(ContentInfo, :count).by(-1)
    end

    it "redirects to the content_infos list" do
      content_info = ContentInfo.create! valid_attributes
      delete :destroy, :id => content_info.id.to_s
      response.should redirect_to(content_infos_url)
    end
  end

end
