require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LessonPagesController do

  # This should return the minimal set of attributes required to create a valid
  # LessonPage. As you add validations to LessonPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lesson_pages as @lesson_pages" do
      lesson_page = LessonPage.create! valid_attributes
      get :index
      assigns(:lesson_pages).should eq([lesson_page])
    end
  end

  describe "GET show" do
    it "assigns the requested lesson_page as @lesson_page" do
      lesson_page = LessonPage.create! valid_attributes
      get :show, :id => lesson_page.id.to_s
      assigns(:lesson_page).should eq(lesson_page)
    end
  end

  describe "GET new" do
    it "assigns a new lesson_page as @lesson_page" do
      get :new
      assigns(:lesson_page).should be_a_new(LessonPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested lesson_page as @lesson_page" do
      lesson_page = LessonPage.create! valid_attributes
      get :edit, :id => lesson_page.id.to_s
      assigns(:lesson_page).should eq(lesson_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LessonPage" do
        expect {
          post :create, :lesson_page => valid_attributes
        }.to change(LessonPage, :count).by(1)
      end

      it "assigns a newly created lesson_page as @lesson_page" do
        post :create, :lesson_page => valid_attributes
        assigns(:lesson_page).should be_a(LessonPage)
        assigns(:lesson_page).should be_persisted
      end

      it "redirects to the created lesson_page" do
        post :create, :lesson_page => valid_attributes
        response.should redirect_to(LessonPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lesson_page as @lesson_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonPage.any_instance.stub(:save).and_return(false)
        post :create, :lesson_page => {}
        assigns(:lesson_page).should be_a_new(LessonPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonPage.any_instance.stub(:save).and_return(false)
        post :create, :lesson_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lesson_page" do
        lesson_page = LessonPage.create! valid_attributes
        # Assuming there are no other lesson_pages in the database, this
        # specifies that the LessonPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LessonPage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lesson_page.id, :lesson_page => {'these' => 'params'}
      end

      it "assigns the requested lesson_page as @lesson_page" do
        lesson_page = LessonPage.create! valid_attributes
        put :update, :id => lesson_page.id, :lesson_page => valid_attributes
        assigns(:lesson_page).should eq(lesson_page)
      end

      it "redirects to the lesson_page" do
        lesson_page = LessonPage.create! valid_attributes
        put :update, :id => lesson_page.id, :lesson_page => valid_attributes
        response.should redirect_to(lesson_page)
      end
    end

    describe "with invalid params" do
      it "assigns the lesson_page as @lesson_page" do
        lesson_page = LessonPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonPage.any_instance.stub(:save).and_return(false)
        put :update, :id => lesson_page.id.to_s, :lesson_page => {}
        assigns(:lesson_page).should eq(lesson_page)
      end

      it "re-renders the 'edit' template" do
        lesson_page = LessonPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonPage.any_instance.stub(:save).and_return(false)
        put :update, :id => lesson_page.id.to_s, :lesson_page => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lesson_page" do
      lesson_page = LessonPage.create! valid_attributes
      expect {
        delete :destroy, :id => lesson_page.id.to_s
      }.to change(LessonPage, :count).by(-1)
    end

    it "redirects to the lesson_pages list" do
      lesson_page = LessonPage.create! valid_attributes
      delete :destroy, :id => lesson_page.id.to_s
      response.should redirect_to(lesson_pages_url)
    end
  end

end
