require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeacherDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # TeacherDetail. As you add validations to TeacherDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all teacher_details as @teacher_details" do
      teacher_detail = TeacherDetail.create! valid_attributes
      get :index
      assigns(:teacher_details).should eq([teacher_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested teacher_detail as @teacher_detail" do
      teacher_detail = TeacherDetail.create! valid_attributes
      get :show, :id => teacher_detail.id.to_s
      assigns(:teacher_detail).should eq(teacher_detail)
    end
  end

  describe "GET new" do
    it "assigns a new teacher_detail as @teacher_detail" do
      get :new
      assigns(:teacher_detail).should be_a_new(TeacherDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested teacher_detail as @teacher_detail" do
      teacher_detail = TeacherDetail.create! valid_attributes
      get :edit, :id => teacher_detail.id.to_s
      assigns(:teacher_detail).should eq(teacher_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeacherDetail" do
        expect {
          post :create, :teacher_detail => valid_attributes
        }.to change(TeacherDetail, :count).by(1)
      end

      it "assigns a newly created teacher_detail as @teacher_detail" do
        post :create, :teacher_detail => valid_attributes
        assigns(:teacher_detail).should be_a(TeacherDetail)
        assigns(:teacher_detail).should be_persisted
      end

      it "redirects to the created teacher_detail" do
        post :create, :teacher_detail => valid_attributes
        response.should redirect_to(TeacherDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teacher_detail as @teacher_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDetail.any_instance.stub(:save).and_return(false)
        post :create, :teacher_detail => {}
        assigns(:teacher_detail).should be_a_new(TeacherDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDetail.any_instance.stub(:save).and_return(false)
        post :create, :teacher_detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teacher_detail" do
        teacher_detail = TeacherDetail.create! valid_attributes
        # Assuming there are no other teacher_details in the database, this
        # specifies that the TeacherDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeacherDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => teacher_detail.id, :teacher_detail => {'these' => 'params'}
      end

      it "assigns the requested teacher_detail as @teacher_detail" do
        teacher_detail = TeacherDetail.create! valid_attributes
        put :update, :id => teacher_detail.id, :teacher_detail => valid_attributes
        assigns(:teacher_detail).should eq(teacher_detail)
      end

      it "redirects to the teacher_detail" do
        teacher_detail = TeacherDetail.create! valid_attributes
        put :update, :id => teacher_detail.id, :teacher_detail => valid_attributes
        response.should redirect_to(teacher_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the teacher_detail as @teacher_detail" do
        teacher_detail = TeacherDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => teacher_detail.id.to_s, :teacher_detail => {}
        assigns(:teacher_detail).should eq(teacher_detail)
      end

      it "re-renders the 'edit' template" do
        teacher_detail = TeacherDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => teacher_detail.id.to_s, :teacher_detail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teacher_detail" do
      teacher_detail = TeacherDetail.create! valid_attributes
      expect {
        delete :destroy, :id => teacher_detail.id.to_s
      }.to change(TeacherDetail, :count).by(-1)
    end

    it "redirects to the teacher_details list" do
      teacher_detail = TeacherDetail.create! valid_attributes
      delete :destroy, :id => teacher_detail.id.to_s
      response.should redirect_to(teacher_details_url)
    end
  end

end
